version: "3.9"

services:
  mc:
  #imagen del servidor 
    image: itzg/minecraft-server:java8-multiarch
    ports:
    #Mapeo de puertos 
      - 25565:25565 
    #Con este parametro aceptamos las condiciones de hacer un servidor de Minecraft Ofical
    environment:
      EULA: "TRUE"
      VERSION: 1.12.2
      TYPE: FORGE
      FORGE_VERSION: 14.23.5.2860
      MEMORY: 8G
      DEBUG: "true"
      OPS: ecoblaxter
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # Carpeta donde se guardaran los datos del servidor
      - ./minecraft-data:/data